### ISSUE TITLE
Wrap Read Issue

### ISSUE THREAD

**Issue by YeuzhiHere** [shahbazdullu/AHB-Lite-Slave-VIP#1]
Mr. Shahbaz, I appreciate your effort for creating and providing this SV based environment to verify AHB-Lite Slave. But I found an issue that while reading wrap sequences, first sequence transaction type should be non-sequential while remaining sequences should be sequential. I found no such clause or condition in your environment.

**Comment by YeuzhiHere** [comment]
But if we add such condition in your environment, wrap cases works perfectly.

**Comment by shahbazdullu** [comment]
Thank for pointing it out. The task has been updated. You can clone and re-use the updated files angain.
